### ISSUE TITLE
[Auto Deploy] OCI 내 docker 컨테이너 자동 Release

### ISSUE THREAD

**Issue by Rick00Kim** [Rick00Kim/Debate_project#13]
## GOAL
main 브랜치의 업데이트가 발생할 시, OCI내 컨테이너를 최신화

## TASK
- [x] 1. main 으로 Pull request 작성시, 각 컴포넌트의 빌드 실행(For Test)
       #9
- [x] 2. 브랜치 업데이트시 Docker hub로 새로운 이미지 Push
       #10
       #11
       #12
- [x] 3. 지정 OCI 가상머신으로 SSH 통신을 통한 docker-compose 재실행
       #14

### [TASK 3] 과제
1. scp tool을 이용한 Docker container 실행용 docker-compose 파일 송신
2. ssh tool를 통해 지정 OCI 가상머신으로 통신후 docker-compose 실행 (Command 이용)

### 계획
브랜치: `feature/build-workflow-for-auto-deploy`, `develop`

1. github actions용 workflow yaml 수정
2. develop 브랜치를 활용해 품질확인

**Comment by Rick00Kim** [comment]
### Memo (2022/04/25)

Github actions를 통한 OCI client 설치과정중, 환경변수 설정이 실패함.
- 실행 명령어
   `echo "::add-path::/home/runner/bin"`

- 에러 메세지
   ```text
   Error: Unable to process command '::add-path::/home/runner/bin' successfully.
   Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command 
   execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
   ```

- 해당기능 릴리스 소식
   https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

- 해결방안
   [add-path] -> https://github.community/t/deprecated-add-path/136621
    126b428aa37650750f69cb4db6d9220d4f14b56c

   [set-env] -> https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files
   9b7964995242ade1d2b6b043e77ae50b195d9273
